DROP TABLE IF EXISTS quizzes CASCADE;
CREATE TABLE cars (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  make VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  colour VARCHAR(255) NOT NULL,
  plate_number VARCHAR(255) NOT NULL
);