DROP TABLE IF EXISTS bookings CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  spot_id INTEGER NOT NULL REFERENCES spots(id) ON DELETE CASCADE,
  car_id INTEGER NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  start_date_time SMALLDATETIME NOT NULL,
  end_date_time SMALLDATETIME NOT NULL
);