DROP TABLE IF EXISTS bookmarked_spots CASCADE;
CREATE TABLE bookmarked_spots (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  spot_id INTEGER NOT NULL REFERENCES spots(id) ON DELETE CASCADE
);