DROP TABLE IF EXISTS spot_ratings CASCADE;
CREATE TABLE spot_ratings (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  spot_id INTEGER NOT NULL REFERENCES spots(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL
);